//中文
var zh = {
	//用户须知
	la_noteTit: '用户须知',
	la_noteWel: '欢迎您使用康加智能筛查机器人服务，本人已经阅读康加智能筛查机器人服务条款并同意本声明。',
	la_noto1: '1.康加智能筛查机器人是针对亚健康人群进行数据采集设备，并非医疗器械设备，康加智能筛查机器人所有资料及数据报告仅供参考使用，不作为个人健康状况的医疗目的衡量标准，也不能替代医生和其他医务人员的专业建议。',
	la_note2: '2.任何情况下，康加智能筛查机器人所提供数据仅为提升用户体验所用，用户对于其自身健康状况的最终评估仅来自于专业医疗机构的检测手段，康加智能筛查机器人对于采集数据不做任何形式的保证，不保证所提供数据满足用户的要求，对采集结果的安全性、正确性、及时性均不做担保。故本公司不对因使用本品提供的数据而导致之损失或损害承担任何直接或间接责任。',
	la_note3: '3.康加智能筛查机器人是为亚健康人群设计，以中医数字化技术、脉搏波检测技术、生物电阻抗检测技术为基础，经过科学及实践测算出来，并非特别针对残缺人士及疾病患者，此类人群使用可能会出现个别指标测量不精准。',
	la_note4: '4.健康分析报告说明：⽬的实现⾃我预防保健。世界卫⽣组织研究报告表明，1/3的疾病是可以通过预防保健避免的，1/3的疾病可以通过信息的有效沟通来提⾼治疗的效果。要从疾病管理为主转向预防保健和⾃我保健为主，康加智能筛查机器人通过移动互联和康加云健康系统为用户提供⽐较全⾯、系统的健康分析，从⽽有重点地进⾏⾃我预防、有重点地去医疗机构检查！',
	la_node5: '5.本报告主要起预警作⽤，对检测出来⾃⼰也知道的慢性健康问题，继续加以重视；对检测出来提示预警或⾃⼰原来不知道的健康问题，可能仅是⼀种早期症状，应引起重视，但不必紧张，或者去医院做进⼀步检查。或因本次所查范围所限未能发现到的情况，仍按原诊断及治疗。本次健康分析报告仅根据本次所查范围所做，可能难以全⾯反映您的健康状况。如有不适症状出现请到相应医院专科就诊。',
	la_note6: '6.康加智能筛查机器人评估报告推送的内容，含膳食建议、营养建议、运动建议、健康食谱、调养方法等均作为个人健康管理所需的参考，不作为处方。本公司不对通过康加智能筛查机器人在其信息平台提供的相关产品或服务做任何担保。',
	la_note7: '7.康加智能筛查机器人是基于假定用户正常情况下进行的数据采集，采集结果每时每刻都在发生变化，所以建议每天测量选择固定时间点，最好是空腹平静心态下测量会更有效。用户通过康加智能筛查机器人获取材料或数据由您自己承担风险，同时您将对使用此类材料或数据而导致的人身或财产损失承担全部责任。',
	la_note8: '8.因健康报告里面包含个人隐私问题，当用户分享给它人或朋友圈时，即表示该用户自行同意把隐私公开。',
	la_note9: '9.用户扫描二维码需要先关注康加公众号/或下载使用康加APP，因其数据报告跟公众号/或APP绑定在一起，会保留历史纪录，方便进行长期数据追踪和分析。',
	la_note10: '10、用户在注册使用服务的过程中，同意授权本公司通过电话、短信等形式，向用户发送相关通知以及产品推荐服务。',
	la_note11: '11.本公司重视对用户隐私的保护，保护隐私是本公司的一项基本政策。您提供的登记资料及本公司保留的有关您的若干其他个人资料将受到中国有关隐私的法律法规的保护。康加健康报告会引用您的基础数据进行大数据建模，非经用户亲自许可或根据相关法律的强制性规定，本公司不会主动的将您的身份信息泄露给其他任何第三方。',
	la_note12: '12.本公司有权在必要时修改服务条款，服务条款一旦发生变动，将会在相关页面上公布修改后的服务条款。如果不同意所改动的内容，用户应主动取消此项服务。如果用户继续使用服务，则视为接受服务条款的变动。',
	la_note13: '13.凡以任何方式登录康加智能筛查机器人， 或对您使用康加智能筛查机器人、网络平台、与本公司相关的任何内容、服务均视为自愿接受康加智能筛查机器人声明的约束。无论在任何原因下（包括但不限于疏忽原因），对您或任何人通过使用康加智能筛查机器人所导致的损失或损害（包括直接、间接的损失或损害），责任均由使用者自行承担（除非该等损失系由本公司产品质量不达标所致）。',
	la_k_company: '康加公司 版权所有 请勿抄袭！',
	
	//说明 
	la_instructionTit: '说明',
	la_instructionWel: '欢迎您查看健康报告使用帮助！',
	//2.0
	la_instruction1: '一、如何查看您的健康报告？',
	la_instruction1_1: '1、综合评估：智能筛查机器人针对您的整体健康状况给予综合评估得分，分值代表了整体的健康情况，分值越高说明您的身体越好、分值较低时说明您处于亚健康状态；',
	la_instruction1_2: '2、十大系统：智能筛查机器人针对人体10大系统进行评估，分值越高说明您的身体越好，分值越低则反之说明您处于相对比较严重的亚健康状态；',
	la_instruction1_3: '3、健康指标：智能筛查机器人给予10大系统下的健康指标进行评估，评估得分越高分值越高说明您的身体越好、分值较低则反之。智能筛查机器人将根据您的详细指标评估结果给予专属的健康改善建议，基于膳食、营养素、运动和生活方式，请您按照建议积极改善生活习惯、调整饮食结构、合理增加运动锻炼（具体详见报告建议）。健康建议将有助于改善您的亚健康状态、全面提升您的身体素质。',
	la_instruction1_4: '4、实时状态：智能筛查机器人针对您的实时状态给予评估，共计有6项状态评估，有助于您及时了解自己的身体状态。',
	la_instruction2: '二、关于报告中提示的问题？',
	la_instruction2_1: '本报告主要起预警作用，对检测出来您已知的慢性健康问题，继续加以重视；对检测出来提示预警或原来您不知道的健康问题，可能仅是⼀种早期症状，应引起重视，但不必紧张，或者去医院做进⼀步检查。或因本次所筛查范围所限未能发现到的情况，仍按原诊断及治疗。',
	la_instruction3: '三、关于您的专属健康改善建议？',
	la_instruction3_1: '报告中推送的内容，包含膳食建议、运动建议、健康食谱、营养素建议、调养方法等均作为个人健康管理所需的参考，不作为处方，用户可根据自身情况进行合理搭配选择，旨在希望您通过健康饮食及合理的生活方式提升或改善您的健康状况。',
	//3.0
	la_instr1: '一、如何查看您的健康报告？',
	la_instr1_1: '1、综合分数：智能健康筛查机器人针对您的整体健康状况给予综合评估得分，分值代表了整体的健康情况，分值越高说明您的身体越好、分值较低时说明您处于亚健康状态；',
	la_instr1_2: '2、亚健康风险：包括最佳状态、良好状态、一级风险、二级风险、三级风险五个维度。三级风险级别最高，提示您发生疾病的可能性较大，需要重点关注健康。',
	la_instr1_3: '3、快乐指数：快乐指数是人们对客观事物态度的体验，是人们的需要是否获得满足的反映，积极的情绪可以提高机体的免疫功能，促进健康；消极的情绪可诱发疾病的发生，降低治疗的效果。',
	la_instr1_4: '4、睡眠质量：反映您的睡眠状况是否良好。',
	la_instr1_5: '5、实时状态：智能健康筛查机器人针对您的实时状态给予评估，共计有5项状态评估，有助于您及时了解自己的身体状态。',
	la_instr1_6: '6、BMI：是目前国际上常用的衡量人体体重以及是否健康的主要标准。',
	la_instr1_7: '7、身体机能评估：评估您身体6大机能状况，有针对性的提醒您需要重点关注的部分。',
	la_instr1_8 '8、皮肤评估：对皮肤整体情况进行分析和评估。',
	la_instr2: '二、关于报告中提示的问题？',
	la_instr2_1: '本报告主要起预警作用，对检测出来您已知的慢性健康问题，继续加以重视；对检测出来提示预警或原来您不知道的健康问题，可能仅是一种早期症状，应引起重视，或者去医院做进一步检查。或因本次检测范围所限未能发现到的情况，建议仍按原诊断治疗。',
	la_instr3: '三、关于您的专属健康改善建议？',
	la_instr3_1: '报告中推送的健康建议内容，包含膳食建议、营养建议、运动及生活方式建议三大模块，可作为个人健康管理方案的参考，不作为处方，用户可根据自身情况进行合理搭配选择，希望帮助您改善健康状况。',
	la_instr4: '四、关于您的专属健康食谱？',
	la_instr4_1: '根据您的健康状况，由专业营养师为您推荐一周的食谱，点击食谱中菜名即可查看餐品标准配比及营养成分。 如果您存在基础病，请以遵医嘱为先。',
	la_instr5: '五、关于历史趋势？',
	la_instr5_1: '持续监测可了解健康趋势变化。',

};
//英语
var en = {
	//用户须知
	la_noteTit: 'User Notes',
	la_noteWel: 'Welcome to use Konstar Intelligent Screening Robot service. I have read the service terms of Konstar Intelligent Screening Robot and agree to this statement.',
	la_noto1: '1. Konstar Intelligent Screening Robot is a data collection device for sub-healthy people, but not a medical device. All the materials and data reports of Konstar Intelligent Screening Robot are for reference only, are not used as a standard for measuring the individual health status for medical purpose, and cannot replace the professional advices of doctors and other medical personnel.',
	la_note2: '2. In any case, the data provided by Konstar Intelligent Screening Robot are only used for improving the user experience. User’s final evaluation of his/her health only comes from the detection means of professional medical institutions. Konstar Intelligent Screening Robot doesn’t provide any form of guarantee for data collection, and does not guarantee that the data provided meets the requirements of user, and does not guarantee the safety, accuracy and timeliness of the results collected. Therefore, our company shall not be directly or indirectly liable for any loss or damage caused by the data provided due to the use of the product.',
	la_note3: '3. Konstar Intelligent Screening Robot is designed for the sub-healthy population. Based on the digital technology of traditional Chinese medicine, pulse wave detection technology and bioelectrical impedance detection technology, it measures and calculates through science and practice, and is not specifically targeted at the disabled and patients with diseases. Individual indicators may be measured inaccurately when such population uses the product.',
	la_note4: '4. Description of the health analysis report: The purpose is to realize self preventive care. The research report of World Health Organization has shown that 1/3 of the diseases can be avoided by preventive care, and the treatment effect of 1/3 of the diseases can be improved through the effective communication of information. We shall change from disease management to preventive care and self care. Konstar Intelligent Screening Robot provides users with a complete and systematic health analysis through the mobile Internet and Konstar cloud health system for self prevention and examination in the medical institutions with targets!',
	la_node5: '5. This report is mainly for early warning. The user can continue to pay attention to the chronic health problems detected which he/she knows; and should pay attention to the health problems detected and warned which he/she does not know or may be only an early symptom without being nervous or go to the hospital for further examination. Or the original diagnosis and treatment shall be applied for the conditions which are not detected due to the limited examination range. This health analysis report is only prepared according to the examination range. It may be difficult to fully reflect your health conditions. If you have any discomfort, please go to the special department of corresponding hospital.',
	la_note6: '6. The contents pushed by the evaluation report of Konstar Intelligent Screening Robot including diet suggestions, nutrition suggestions, sports suggestions, healthy recipes, methods of recuperation, etc. are all the required references for personal health management, but not prescriptions. Our company does not guarantee relevant products or services provided on its information platform by Konstar Intelligent Screening Robot.',
	la_note7: '7. Konstar Intelligent Screening Robot collects data based on the assumption that the user is under normal conditions, and the collection results are changing all the time, so it is recommended to select a fixed time point for daily measurement, and it is better to measure with an empty belly and a calm state of mind, which will be more effective. The user acquires materials or data through Konstar Intelligent Screening Robot at your own risk. At the same time, you shall bear all the personal or property losses caused by the use of such materials or data.',
	la_note8: '8. Because the health report contains personal privacy issues, when the user shares it with others or in the circle of friends, it means that the user agrees to make the privacy public.',
	la_note9: '9. The user needs to firstly pay attention to Konstar’s official account/or download and use Konstar APP before scanning the QR code. Because the data report is bound to the official account/or APP, thus, the historical records will be kept for long-term data tracking and analysis.',
	la_note10: '10. Our company attaches importance to the protection of user’s privacy, which is a basic policy of our company. The registration information you provide and certain other personal information we kept about you will be protected by China’s relevant privacy laws and regulations. Konstar Health Report will use your basic data for big data modeling, and our company will not voluntarily disclose your identity information to any other third party without the user’s permission or according to the mandatory provisions of relevant laws.',
	la_note11: '11. Our company has the right to modify the terms of service if necessary. In case of any change to the terms of service, the revised terms of service will be published on the relevant pages. If you do not agree with the content revised, you should promptly cancel the service. If the user continues to use the service, it is deemed to accept the change of terms of service.',
	la_note12: '12. Any access to Konstar Intelligent Screening Robot in any way or your use of Konstar Intelligent Screening Robot, network platform and any content and service related to our company shall be deemed as the voluntary acceptance of the statement of Konstar Intelligent Screening Robot. No matter for any reason (including but not limited to negligence), the user shall be liable for any loss or damage (including direct and indirect loss or damage) caused by youself or anyone by using Konstar Intelligent Screening Robot (unless such loss is caused by the substandard quality of our products).',
	la_note13:'',
	la_k_company: 'Konstar Company All rights reserved',
	
	//说明 
	la_instructionTit: 'Instructions',
	la_instructionWel: 'Welcome to view the health report and use the help!',
	//2.0
	la_instruction1: 'I. How to view your health report?',
	la_instruction1_1: '1.  Comprehensive evaluation: The intelligent screening robot gives a comprehensive evaluation score for your overall health conditions. The score represents the overall health condition. The higher the score is, the healthier you are. The lower score indicates the sub-health staus;',
	la_instruction1_2: '2.  Ten systems: The intelligent screening robot evaluates 10 systems of the human body. The higher the score is, the healthier you are. Otherwise, the lower score indicates the relatively serious sub-health status.',
	la_instruction1_3: '3.  Health indicators: The intelligent screening robot evaluates the health indicators under the 10 systems. The higher the score is, the healthier you are. Otherwise, the lower the score is, the unhealthier you are. The intelligent screening robot will provide exclusive health improvement suggestions based on the evaluation results of your detailed indicators. Based on diet, nutrients, sports and lifestyle, please actively improve your living habits, adjust your diet structure and reasonably increase exercise according to the suggestions (see the report for details). Health suggestions will help you to improve the sub-health status, and improve your overall physical fitness.',
	la_instruction1_4: '4.  Real-time status: The intelligent screening robot will evaluate your real-time status, and there are 6 status evaluations in total, which can help you to know your physical status in a timely manner.',
	la_instruction2: 'II. About the problems indicated in the report?',
	la_instruction2_1: 'This report is mainly for early warning. You can continue to pay attention to your known chronic health problems detected, and pay attention to the health problems detected and warned which you do not know or may be only an early symptom without being nervous or go to the hospital for further examination. Or the original diagnosis and treatment shall be applied for the conditions which are not detected due to the limited examination range.',
	la_instruction3: 'III. About your exclusive health improvement suggestions?',
	la_instruction3_1: 'The contents pushed by the report including diet suggestions, sports suggestions, healthy recipes, nutrition suggestions, methods of recuperation, etc., are all the required references for personal health management, but not prescriptions. The user can choose reasonable collocation according to his/her own situation, aiming to improve your health conditions through healthy diet and reasonable lifestyle.',
	//3.0
	la_instr1: 'I. How to view your health report?',
	la_instr1_1: '1. Comprehensive score: The intelligent health screening robot gives a comprehensive evaluation score for your overall health conditions. The score represents the overall health conditions. The higher the score is, the healthier you are. The lower score indicates the sub-health status;',
	la_instr1_2: '2. Sub-health risks: They include five dimensions such as optimal status, good status, Level-1 risk, Level-2 risk and Level-3 risk. Level-3 risk has the highest risk level, indicating that you are more likely to have a disease and need to focus on health.',
	la_instr1_3: '3. Happiness index: Happiness index is the experience of people’s attitude towards objective things and the reflection of whether people’s needs are met. Positive emotions can improve the immune function of the body and promote health; Negative emotions can induce diseases and reduce the effect of treatment.',
	la_instr1_4: '4. Sleep quality: It reflects whether your sleep condition is good or not.',
	la_instr1_5: '5. Real-time status: The intelligent health screening robot evaluates your real-time status, and there are 5 status evaluations in total, which can help you to know your physical status in a timely manner.',
	la_instr1_6: '6. BMI: It is currently the main international standard for measuring body weight and health.',
	la_instr1_7: '7. Body function evaluation: It evaluates the six major functions of your body, and purposefully reminds you of the key parts.',
	la_instr1_8 '8. Skin evaluation: It analyzes and evaluates the overall conditions of the skin.',
	la_instr2: 'II. About the problems indicated by the report?',
	la_instr2_1: 'This report is mainly for early warning. You can continue to pay attention to your known chronic health problems detected, and pay attention to the health problems detected and warned which you do not know or may be only an early symptom without being nervous or go to the hospital for further examination. Or the original diagnosis and treatment shall be applied for the conditions which are not detected due to the limited examination range.',
	la_instr3: 'III. About your exclusive health improvement suggestions?',
	la_instr3_1: 'The health suggestion contents pushed in the report including three modules like diet suggestions, nutrition suggestions, and sports lifestyle suggestions, are all references for personal health management, but not prescriptions. The user can choose reasonable collocation according to his/her own situation. We hope to help you to improve your health conditions.',
	la_instr4: 'IV. About your exclusive healthy recipes?',
	la_instr4_1: 'According to your health conditions, a professional dietitian will recommend a week’s recipes for you. Click the names of the dishes in the recipes to see the standard proportions and nutritional ingredients. If you have background diseases, please follow your doctor’s advice first.',
	la_instr5: 'V. About the historical trends?',
	la_instr5_1: 'You can know the changes in health trends through continuous monitoring.',
	
}
